FROM microsoft/cntk:latest

RUN locale-gen en_US.UTF-8
   ENV LANG=en_US.UTF-8    \
   LANGUAGE=en_US:en       \
   LC_ALL=en_US.UTF-8      \
   PYTHONIOENCODING=utf-8

ADD requirements.txt /tmp/requirements.txt
RUN bash -c \
     "source /cntk/activate-cntk && \
      pip install -r /tmp/requirements.txt"
